Add user entity and repository.
FearDAR/UsersUpdate pull request #4
Opened 2024-02-08 13:13 UTC by FearDAR

2024-02-08 13:22 UTC, mikhaylovivan90 requested changes

2024-02-08 13:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/User.java
> +package com.example.usersupdate.antiti;
название пакета топ, скрестили муравья и тити.
usersupdate тоже плохо.
если ты хочешь чтобы у тебя доменный слой юзера и хранить энтити там, то я бы сделал так service.user.db

2024-02-08 13:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
мы добавляли сиквенс и у нас стратегия - через сиквенс, можно найти в интернетах как это сделать

2024-02-08 13:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    private String firstName;
тут все очевидно, но для норм практики - добавь джава доки на эти поля

2024-02-08 13:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    public User() {
можешь так оставить, а можешь почитать что такое ломбок хотя бы верхнеуровнево и запилить аннотации @NoArgsConstructor @Getter @Setter

2024-02-08 13:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/UserRepository.java
> +package com.example.usersupdate.antiti;
про пакет уже писал

2024-02-09 09:28 UTC, FearDAR commented on src/main/java/com/example/usersupdate/antiti/User.java
> +package com.example.usersupdate.antiti;
+

2024-02-09 09:33 UTC, FearDAR commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY)
Точно, забыл что в sql скрипте мы добавили сиквенс.

2024-02-09 09:44 UTC, FearDAR commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    private String firstName;
Добавил

2024-02-09 10:20 UTC, FearDAR commented on src/main/java/com/example/usersupdate/antiti/User.java
> +    public User() {
Прописал аннотации ломбок

2024-02-09 12:20 UTC, mikhaylovivan90 commented on src/main/java/com/example/usersupdate/antiti/User.java
> +package com.example.usersupdate.antiti;
ток ща понял, usersupdate это оказывается корневой пакет, я думал тока com.example корневой, тогда вместо серивс надо как нить назвать, хотя бы dima а уже внутри service папку

2024-02-09 12:22 UTC, mikhaylovivan90 requested changes

2024-02-09 12:22 UTC, mikhaylovivan90 commented on build.gradle
>      //implementation 'org.flywaydb:flyway-core:10.7.0'
а эти комменты до сих пор чтоль в билд гредл, надо удалить

2024-02-09 12:22 UTC, mikhaylovivan90 commented on src/main/resources/application.yml
> +
а зачем эти переносы строк?

2024-02-09 12:22 UTC, mikhaylovivan90 commented on src/main/java/com/example/service/user/db/User.java
> +    @Id
сиквенс в итоге не появился, а он нужен

2024-02-09 13:51 UTC, FearDAR commented on build.gradle
>      //implementation 'org.flywaydb:flyway-core:10.7.0'
замержил с мастером, комменты удалились

2024-02-09 13:54 UTC, FearDAR commented on src/main/resources/application.yml
> +
лишние переносы убрал

2024-02-09 14:15 UTC, FearDAR commented on src/main/java/com/example/service/user/db/User.java
> +    @Id
Добавил сиквенс

2024-02-09 14:16 UTC, FearDAR commented on src/main/resources/application.yml
> +
лишние переносы убрал

2024-02-09 14:43 UTC, merged