Create UserService class. Transfer method create from UserController …
FearDAR/UsersUpdate pull request #7
Opened 2024-03-13 09:57 UTC by FearDAR

…to UserService. Аdd settings for user_id_seq.

2024-03-13 10:13 UTC, mikhaylovivan90 requested changes

2024-03-13 10:13 UTC, mikhaylovivan90 commented on src/main/resources/db/migration/V1__user.sql
> -CREATE SEQUENCE users_id_seq;
так нельзя делать, я уже говорил про чек сумму, миграции не исправляются, пишутся новые которые дополнят/исправят существующие
min value и все остальное необязательно, то как было - было норм

2024-03-13 10:13 UTC, mikhaylovivan90 commented on src/main/java/com/example/project/service/user/UserService.java
> +    @Autowired
какие еще виды инжекта бина ты знаешь?

2024-03-13 10:15 UTC, mikhaylovivan90 requested changes

2024-03-13 10:15 UTC, mikhaylovivan90 commented on src/main/java/com/example/project/service/user/db/User.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_id_seq")
а у тебя точно тут работает, посмотри как в примере, который  скинул прописаны имена

2024-03-13 11:32 UTC, FearDAR commented on src/main/resources/db/migration/V1__user.sql
> -CREATE SEQUENCE users_id_seq;
удалил min value и все остальное

2024-03-13 11:35 UTC, FearDAR commented on src/main/java/com/example/project/service/user/db/User.java
> +    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_id_seq")
как в примере не работает, если я добавляю не "users_id_seq", а "user_gen", то пишет что отношение "users_gen" не существует.

2024-03-13 11:37 UTC, FearDAR commented on src/main/java/com/example/project/service/user/UserService.java
> +    @Autowired
еще знаю @Resource, которая привязывается при указанием имени.

2024-03-15 11:51 UTC, mikhaylovivan90 approved these changes

2024-03-15 11:51 UTC, mikhaylovivan90 commented on src/main/java/com/example/project/service/user/UserService.java
> +    @Autowired
resource вроде про другое
я имел ввиду вот инжект через @Autowired, но есть другие виды и как правило @Autowired практически никогда не используется, а используется другой вид инжекта

2024-03-15 11:51 UTC, merged